license="MIT"

[[mods]]
modId="inmis"
version="${version}"
displayName="Inmis"
description="I need more inventory space!"
authors="Draylar"
credits="shedaniel, OmegaJak"
logoFile="assets/inmis/icon.png"

[[dependencies.inmis]]
modId="neoforge"
type="required"
versionRange="[26.1.2.114,)"
ordering="NONE"
side="BOTH"

[[dependencies.inmis]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.inmis]]
modId="curios"
type="optional"
versionRange="[${curios_version_range},)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="inmis.mixins.json"
